[[plugins]] # プラグインマネージャ
repo = 'Shougo/dein.vim'
hook_add = '''
    autocmd VimEnter * call dein#call_hook('post_source')
'''

[[plugins]] # 非同期処理
repo = 'Shougo/vimproc'
hook_post_update = '''
    let cmd = 'make'
    let g:dein#plugin.build = cmd
'''

[[plugins]] # ステータスライン
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.vimfiles/hook/lightline.vim'

[[plugins]] # ファイルツリー
repo = 'scrooloose/nerdtree'
hook_add = '''
    nnoremap <silent><C-e> :NERDTreeToggle<CR>
    set shell=sh
'''

[[plugins]] # ファイルツリーにGit情報をのせる
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]] # 関数定義とか見れる
repo = 'majutsushi/tagbar'
hook_add = 'source ~/.vimfiles/hook/tagbar.vim'

[[plugins]] # Git操作
repo = 'tpope/vim-fugitive'

[[plugins]] # ファイルの左側にGit情報をのせる
repo = 'airblade/vim-gitgutter'

[[plugins]] # コミットログを出す
repo = 'cohama/agit.vim'

[[plugins]] # 検索
repo = 'rking/ag.vim'
hook_add = 'nnoremap ? :LAg '

[[plugins]] # 非同期シンタックスチェック
repo = 'w0rp/ale'
if = 0

[[plugins]] # vim-lsp用のやつ
repo = 'prabirshrestha/async.vim'

[[plugins]] # language server protocol
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
let g:dls_path = '~/.dub/packages/.bin/dls-latest/dls'
if executable(expand(g:dls_path))
    au User lsp_setup call lsp#register_server({
        \ 'name': 'dls',
        \ 'cmd': {server_info->[expand(g:dls_path), '--stdio']},
        \ 'whitelist': ['d'],
        \ })
endif

let g:lsp_signs_enabled = 1
let g:lsp_diagnostics_echo_cursor = 1
let g:lsp_signs_error = {'text': '✗'}

if &filetype == 'd'
    vnoremap = :LspDocumentRangeFormat<CR>
endif
'''

[[plugins]] # auto completion
repo = 'prabirshrestha/asyncomplete.vim'
hook_add = '''
let g:asyncomplete_smart_completion = 1
let g:asyncomplete_auto_popup = 1
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<cr>"
'''

[[plugins]] # auto completion
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]] # reload
repo = 'lordm/vim-browser-reload-linux'

[[plugins]] # GDB
repo = 'idanarye/vim-vebugger'
hook_add = 'source ~/.vimfiles/hook/vebugger.vim'

[[plugins]] # ファイル名検索ジャンプ
repo = 'ctrlpvim/ctrlp.vim'
hook_add = 'source ~/.vimfiles/hook/ctrlp.vim'

[[plugins]] # カラースキーマ
repo = 'tomasr/molokai'
hook_add = 'set t_Co=256'

[[plugins]] # カラースキーマ
repo = 'vim-scripts/moria'

[[plugins]] # カラースキーマ
repo = 'Haron-Prime/Antares'

[[plugins]] # カラースキーマ
repo = 'freeo/vim-kalisi'
