[[plugins]] # 補間
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertCharPre'
hook_add = 'source ~/.vimfiles/hook/deoplete.vim'
on_event = 'InsertEnter'

[[plugins]] # D言語拡張
repo = 'Sobaya007/deoplete-d'
on_ft = 'd'
on_event = 'InsertEnter'
depends = ['deoplete.nvim']
hook_add = '''
let g:deoplete#sources#d#dcd_server_autostart=1
let g:deoplete#sources#d#dub_import=1
'''

[[plugins]] # D言語ハイライター
repo = 'Sirsireesh/vim-dlang-phobos-highlighter'
on_ft = 'd'
hook_add = '''
let g:d_class_scope_highlight = 1
'''

[[plugins]] # Dのやつ
repo = 'Sobaya007/vim-dutyl'
on_ft = 'd'
hook_source = '''
  nnoremap <C-]> :DUjump<CR>
  let g:dutyl_dontHandleFormat=1
  let g:dutyl_dontHandleIndent=1
'''
hook_post_source = '''
  if !empty(dutyl#projectRoot())
    let g:quickrun_cmd = 'dub'
  endif
'''

[[plugins]] # purescript
repo = 'purescript-contrib/purescript-vim'
on_ft='purescript'

[[plugins]] # purescript
repo = 'FrigoEU/psc-ide-vim'
on_ft='purescript'

[[plugins]] # スニペット
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_ft = ['snippet']
on_event = 'InsertEnter'
depends = ['neosnippet-snippets']

[[plugins]] # スニペットの内容
repo = 'Shougo/neosnippet-snippets'
on_event = 'InsertEnter'

# Lang

[[plugins]] #GLSL
repo = 'tikhomirov/vim-glsl'
on_ft = 'glsl'

[[plugins]] # Html5
repo  = 'othree/html5.vim'
on_ft = 'html'

[[plugins]] # Toml
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # Markdown
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown','mkd']

[[plugins]] #LaTex
repo = 'lervag/vimtex'
on_ft = 'tex'
hook_add = 'source ~/.vimfiles/hook/Vim-Latex.vim'
hook_post_source = '''
    :VimtexCompile
'''

[[plugins]] # Rust 
repo = 'rust-lang/rust.vim'
on_ft = 'rust'

[[plugins]] # Japanese doc
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'
hook_add = 'set helplang=ja,en'

[[plugins]] #Java Script
repo = 'pangloss/vim-javascript'
on_ft = 'js'

[[plugins]] #Java Script
repo = 'mattn/emmet-vim'
on_ft = 'html'

[[plugins]] # Markdownがブラウザでプレビューできる
repo = 'euclio/vim-markdown-composer'
on_ft = 'markdown'
hook_add = 'source ~/.vimfiles/hook/vim-markdown-composer.vim'
hook_post_update = '''
  if has('nvim')
    let cmd = 'cargo build --release'
  else
    let cmd = 'cargo build --release --no-default-features --features json-rpc'
  endif
  let g:dein#plugin.build = cmd
'''
