[[plugins]] # プラグインマネージャ
repo = 'Shougo/dein.vim'
hook_add = '''
    autocmd VimEnter * call dein#call_hook('post_source')
'''

[[plugins]] # 非同期処理
repo = 'Shougo/vimproc'
hook_post_update = '''
    let cmd = 'make'
    let g:dein#plugin.build = cmd
'''

[[plugins]] # ステータスライン
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.vimfiles/hook/lightline.vim'

[[plugins]] # ファイルツリー
repo = 'scrooloose/nerdtree'
hook_add = '''
    nnoremap <silent><C-e> :NERDTreeToggle<CR>
    set shell=sh
'''

[[plugins]] # ファイルツリーにGit情報をのせる
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]] # 関数定義とか見れる
repo = 'majutsushi/tagbar'
hook_add = 'source ~/.vimfiles/hook/tagbar.vim'

[[plugins]] # Git操作
repo = 'tpope/vim-fugitive'

[[plugins]] # ファイルの左側にGit情報をのせる
repo = 'airblade/vim-gitgutter'

[[plugins]] # コミットログを出す
repo = 'cohama/agit.vim'

[[plugins]] # 検索
repo = 'rking/ag.vim'
hook_add = 'nnoremap ? :LAg '

#[[plugins]] # 適当に実行
#repo = 'thinca/vim-quickrun'
#hook_add = 'nnoremap <S-r> :QuickRun<CR>'

[[plugins]] # quickrunのhookがいっぱいある
repo = 'osyo-manga/shabadou.vim'

#[[plugins]] # quickfixのエラー箇所をハイライト
#repo = 'jceb/vim-hier'

#[[plugins]] # 非同期シンタックスチェック
#repo = 'osyo-manga/vim-watchdogs'
#depends = ['vimproc', 'vim-quickrun', 'shabadou.vim', 'vim-hier']
#hook_add = 'source ~/.vimfiles/hook/Watchdogs.vim'

[[plugins]] # 非同期シンタックスチェック
repo = 'w0rp/ale'

#[[plugins]]
#repo = 'huawenyu/neogdb.vim'
#hook_add = '''
#let g:neogdb_window = ['backtrace', 'breakpoint']
#'''

[[plugins]] # reload
repo = 'lordm/vim-browser-reload-linux'

[[plugins]] # GDB
repo = 'idanarye/vim-vebugger'
hook_add = 'source ~/.vimfiles/hook/vebugger.vim'

[[plugins]] # ファイル名検索ジャンプ
repo = 'ctrlpvim/ctrlp.vim'
hook_add = 'source ~/.vimfiles/hook/ctrlp.vim'

[[plugins]] # カラースキーマ
repo = 'tomasr/molokai'
hook_add = 'set t_Co=256'

[[plugins]] # カラースキーマ
repo = 'vim-scripts/moria'

[[plugins]] # カラースキーマ
repo = 'Haron-Prime/Antares'

[[plugins]] # カラースキーマ
repo = 'freeo/vim-kalisi'
