[[plugins]] # プラグインマネージャ
repo = 'Shougo/dein.vim'
hook_add = '''
    autocmd VimEnter * call dein#call_hook('post_source')
'''

[[plugins]] # 非同期処理
repo = 'Shougo/vimproc'
hook_post_update = '''
    let cmd = 'make'
    let g:dein#plugin.build = cmd
'''

[[plugins]] # ステータスライン
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.vimfiles/hook/lightline.vim'

[[plugins]] # ファイルツリー
repo = 'scrooloose/nerdtree'
hook_add = '''
    nnoremap <silent><C-e> :NERDTreeToggle<CR>
    set shell=sh
'''

[[plugins]] # ファイルツリーにGit情報をのせる
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]] # 関数定義とか見れる
repo = 'majutsushi/tagbar'
hook_add = 'source ~/.vimfiles/hook/tagbar.vim'

[[plugins]] # Git操作
repo = 'tpope/vim-fugitive'

[[plugins]] # ファイルの左側にGit情報をのせる
repo = 'airblade/vim-gitgutter'

[[plugins]] # コミットログを出す
repo = 'cohama/agit.vim'

[[plugins]] # 検索
repo = 'rking/ag.vim'
hook_add = 'nnoremap ? :LAg '

[[plugins]] #LSP
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
hook_add = '''
let g:LanguageClient_serverCommands = {
    \ 'rust': ['rustup', 'run', 'stable', 'rls'],
    \ 'javascript': ['typescript-language-server', '--stdio'],
    \ 'd': ['~/git/dls/dls', '--init.logFile=/home/sobaya/log.txt']
    \ }
let g:LanguageClient_rootMarkers = {
    \ 'javascript': ['project.json'],
    \ 'rust': ['Cargo.toml'],
    \ 'd': ['dub.json', 'dub.sdl'],
    \ }
nnoremap <C-L> :call LanguageClient_contextMenu()<CR>
nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>
nnoremap <silent> <C-]> :call LanguageClient#textDocument_definition()<CR>
nnoremap <silent> <F2> :call LanguageClient#textDocument_rename()<CR>
'''

[[plugins]] # html
repo = 'mattn/emmet-vim'

[[plugins]] # reload
repo = 'lordm/vim-browser-reload-linux'

[[plugins]] # GDB
repo = 'idanarye/vim-vebugger'
hook_add = 'source ~/.vimfiles/hook/vebugger.vim'

[[plugins]] # ファイル名検索ジャンプ
repo = 'ctrlpvim/ctrlp.vim'
hook_add = 'source ~/.vimfiles/hook/ctrlp.vim'

[[plugins]] # カラースキーマ
repo = 'tomasr/molokai'
hook_add = 'set t_Co=256'

[[plugins]] # カラースキーマ
repo = 'vim-scripts/moria'

[[plugins]] # カラースキーマ
repo = 'Haron-Prime/Antares'

[[plugins]] # カラースキーマ
repo = 'freeo/vim-kalisi'
