[[plugins]] # 補間
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertCharPre'
hook_add = 'source ~/.vimfiles/hook/deoplete.vim'
on_event = 'InsertEnter'

[[plugins]] # スニペット
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_ft = ['snippet']
on_event = 'InsertEnter'
depends = ['neosnippet-snippets']

[[plugins]] # スニペットの内容
repo = 'Shougo/neosnippet-snippets'
on_event = 'InsertEnter'

[[plugins]] # D言語ハイライター
repo = 'Sirsireesh/vim-dlang-phobos-highlighter'
on_ft = 'd'
hook_add = '''
let g:d_class_scope_highlight = 1
'''

[[plugins]] # scala
repo = 'derekwyatt/vim-scala'
on_ft='scala'

[[plugins]] # purescript
repo = 'purescript-contrib/purescript-vim'
on_ft='purescript'

[[plugins]] # purescript
repo = 'FrigoEU/psc-ide-vim'
on_ft='purescript'

# Lang

[[plugins]] #GLSL
repo = 'tikhomirov/vim-glsl'
on_ft = 'glsl'

[[plugins]] # Html5
repo  = 'othree/html5.vim'
on_ft = 'html'

[[plugins]] # Toml
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # Markdown
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown','mkd']
hook_add = 'let g:vim_markdown_folding_disabled = 1'

[[plugins]] #LaTex
repo = 'lervag/vimtex'
on_ft = ['tex', 'plaintex']
hook_add = 'source ~/.vimfiles/hook/Vim-Latex.vim'

[[plugins]] # Rust 
repo = 'rust-lang/rust.vim'
on_ft = 'rust'

[[plugins]] # Vue 
repo = 'posva/vim-vue'
on_ft = 'vue'

[[plugins]] # Japanese doc
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'
hook_add = 'set helplang=ja,en'

[[plugins]] #Java Script
repo = 'pangloss/vim-javascript'
on_ft = 'js'

[[plugins]] #Java Script
repo = 'othree/yajs.vim'
on_ft = 'js'

[[plugins]] #HTML
repo = 'mattn/emmet-vim'
on_ft = 'html'

[[plugins]] #fish
repo = 'dag/vim-fish'
on_ft = 'fish'

[[plugins]] # Markdownがブラウザでプレビューできる
repo = 'euclio/vim-markdown-composer'
on_ft = 'markdown'
hook_add = '''
let g:markdown_composer_open_browser=0
let g:markdown_composer_autostart=0
'''
hook_post_update = '''
  if has('nvim')
    let cmd = 'cargo build --release'
  else
    let cmd = 'cargo build --release --no-default-features --features json-rpc'
  endif
  let g:dein#plugin.build = cmd
'''
